#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /
    controller: App\Controller\StartPage::showStartPage
login:
    path: /login
    controller: App\Controller\LoginController::route

administration:
    path: /administration/{adminId}
    controller: App\Controller\AdministrationController::showAdminPage
    requirements:
        adminId: '\d+'

profile:
    path: /profile/{userId}
    controller: App\Controller\ProfileController::showProfile
    requirements:
        userId: '\d+'

signError:
    path: /sign_up_error
    controller: App\Controller\StartPage::showErrorPage

bdError:
    path: /bd_error
    controller: App\Controller\StartPage::showBdErrorPage

userNotFound:
    path: /userNotFound
    controller: App\Controller\StartPage::showUserNotFound

addPost:
    path: /profile/add_post
    controller: App\Controller\ProfileController::addNewPost

updatePost:
    path: /profile/update_post
    controller: App\Controller\ProfileController::updatePost

updateName:
    path: /profile/update_name
    controller: App\Controller\ProfileController::updateName

updatePassword:
    path: /profile/update_password
    controller: App\Controller\ProfileController::updatePassword

updatePhoto:
    path: /profile/update_photo
    controller: App\Controller\ProfileController::updatePhoto

updateUserName:
    path: /administration/update_user_name
    controller: App\Controller\AdministrationController::updateUserName

updateUserPassword:
    path: /administration/change_password
    controller: App\Controller\AdministrationController::changePassword

addNewUser:
    path: /administration/new_user
    controller: App\Controller\AdministrationController::addNewUser

deleteUser:
    path: /administration/delete_user
    controller: App\Controller\AdministrationController::removeUser