#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
    path: /

login:
    path: /login

administration:
    path: /administration/{adminId}

profile:
    path: /profile/{userId}

userBlocked:
    path: /user_blocked

userNotFound:
    path: /user_not_found

addPost:
    path: /profile/{userId}/add_post

updatePost:
    path: /profile/{userId}/update_post

updateName:
    path: /profile/{userId}/update_name

updatePassword:
    path: /profile/{userId}/update_password

updatePhoto:
    path: /profile/{userId}/update_photo

updateUserName:
    path: /administration/{adminId}/change_user_name

updateUserPassword:
    path: /administration/{adminId}/change_password

addNewUser:
    path: /administration/{adminId}/new_user

deleteUser:
    path: /administration/{adminId}/delete_user

